#!/bin/bash
echo "🗄️  Steinweg Dock - PostgreSQL Setup"
echo "====================================="
echo ""
echo "This script helps you switch from SQLite to PostgreSQL for production."
echo ""
echo "Step 1: Change Prisma provider"
echo "  Open prisma/schema.prisma"
echo '  Change: provider = "sqlite"'
echo '  To:     provider = "postgresql"'
echo ""
echo "Step 2: Set DATABASE_URL"
echo "  Set your PostgreSQL connection string as DATABASE_URL"
echo "  Example: postgresql://user:password@host:5432/dbname"
echo ""
echo "Step 3: Run migrations"
echo "  npx prisma migrate dev --name init"
echo "  npx prisma migrate deploy  # on Vercel"
echo ""
echo "Step 4: Seed the database"
echo "  After deploying, visit your app and click 'Load Demo Data'"
echo ""
echo "Free PostgreSQL providers:"
echo "  - Vercel Postgres: https://vercel.com/storage"
echo "  - Supabase: https://supabase.com"
echo "  - Neon: https://neon.tech"
